name: islam
description: A personal App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.5-beta+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  image_picker: ^1.0.4
  rename_app: ^1.6.2
  appwrite: ^15.0.0 
  flutter_web_auth_2: 3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700

  assets:
    - assets/images/ios_wallpaper.jpg
    - assets/images/wallpaper1.jpg
    - assets/images/wallpaper2.jpg
    - assets/images/wallpaper3.jpg
